"use client"

export default function places() {

   const arr_of_places = [

        "Paris, France",
        "Rome, Italy",
        "London, UK",
        "Barcelona, Spain",
        "Santorini, Greece",
        "Venice, Italy",
        "Berlin, Germany",
        "Amsterdam, Netherlands",
        "Prague, Czech Republic",
        "Florence, Italy",
        "Tokyo, Japan",
        "Kyoto, Japan",
        "Bangkok, Thailand",
        "Beijing, China",
        "Bali, Indonesia",
        "Singapore",
        "Seoul, South Korea",
        "Jaipur, India",
        "Hanoi, Vietnam",
        "Phuket, Thailand",
        "New York City, USA",
        "Los Angeles, USA",
        "San Francisco, USA",
        "Toronto, Canada",
        "Vancouver, Canada",
        "Las Vegas, USA",
        "Mexico City, Mexico",
        "Havana, Cuba",
        "Orlando, USA",
        "Quebec City, Canada",
        "Cape Town, South Africa",
        "Marrakech, Morocco",
        "Cairo, Egypt",
        "Victoria Falls, Zambia/Zimbabwe",
        "Nairobi, Kenya",
        "Tunis, Tunisia",
        "Zanzibar, Tanzania",
        "Fez, Morocco",
        "Maasai Mara, Kenya",
        "Mount Kilimanjaro, Tanzania",
        "Sydney, Australia",
        "Melbourne, Australia",
        "Auckland, New Zealand",
        "Queenstown, New Zealand",
        "Fiji",
        "Great Barrier Reef, Australia",
        "Tasmania, Australia",
        "Bora Bora, French Polynesia",
        "Rotorua, New Zealand",
        "Palau",
        "Dubai, UAE",
        "Petra, Jordan",
        "Jerusalem, Israel",
        "Doha, Qatar",
        "Abu Dhabi, UAE",
        "Istanbul, Turkey",
        "Muscat, Oman",
        "Tel Aviv, Israel",
        "Riyadh, Saudi Arabia",
        "Cappadocia, Turkey",
        "Rio de Janeiro, Brazil",
        "Buenos Aires, Argentina",
        "Machu Picchu, Peru",
        "Cartagena, Colombia",
        "Santiago, Chile",
        "Galápagos Islands, Ecuador",
        "Cusco, Peru",
        "Patagonia, Argentina/Chile",
        "Lima, Peru",
        "Salvador, Brazil",
        "Havana, Cuba",
        "San Juan, Puerto Rico",
        "Montego Bay, Jamaica",
        "Panama City, Panama",
        "Antigua, Guatemala",
        "Tulum, Mexico",
        "San José, Costa Rica",
        "Belize City, Belize",
        "Roatán, Honduras",
        "Punta Cana, Dominican Republic",
        "Maldives",
        "Hawaii (Big Island), USA",
        "Maui, Hawaii",
        "Seychelles",
        "Santorini, Greece",
        "Ibiza, Spain",
        "Corsica, France",
        "Malta",
        "Mykonos, Greece",
        "Sardinia, Italy",
        "Ljubljana, Slovenia",
        "Reykjavik, Iceland",
        "Dubrovnik, Croatia",
        "Bruges, Belgium",
        "Tallinn, Estonia",
        "Vilnius, Lithuania",
        "Bled, Slovenia",
        "Ghent, Belgium",
        "Mostar, Bosnia and Herzegovina",
        "Brasov, Romania"
        
        ]
        
        // for (let place of arr_of_places) {
        //     console.log(place)
        // }

    return (
        <div>
            
        </div>
    )
}